MoviesManagement/MoviesManagement/Models/TvItemViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace MoviesManagement.Models
{
    public class TvItemViewModel
    {
        public MovieViewModel Movie { get; set; }
        public SelectList Emissions { get; set; }
        public string Item { get; set; }
    }
}

MoviesManagement/MoviesManagement/Models/TvItemsViewModel.cs
using Movies.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesManagement.Models
{
    public class TvItemsViewModel
    {
        public IList<TvItemViewModel> TvItems { get; set; }
        public string Item { get; set; }
    }
}

MoviesManagement/MoviesManagement/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using MoviesManagement.Dtos;
using MoviesManagement.Mappers;
using MoviesManagement.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MoviesManagement.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IApiClient apiClient;
        private readonly ITvItemsMapper mapper;

        public MoviesController(IApiClient apiClient, ITvItemsMapper mapper)
        {
            this.apiClient = apiClient;
            this.mapper = mapper;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var movies = await apiClient.GetAsync<IList<Movie>>(@"/api/movies");
            var model = movies.Select(mapper.MapMovie).ToList();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            return await Task.FromResult(View("Create"));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var movie = await apiClient.GetAsync<Movie>(@$"/api/movies/{id}");
            var vm = mapper.MapEditMovieRequest(movie);
            vm.Id = movie.Id;
            return await Task.FromResult(View("Edit", vm));
        }

        public async Task<IActionResult> Record(int id)
        {
            var movie = await apiClient.GetAsync<Movie>(@$"/api/movies/{id}");
            var vm = mapper.MapRecordMovieRequest(movie);
            vm.Id = movie.Id;

            return await Task.FromResult(View("Record", vm));

        }
        public async Task<IActionResult> Delete(int id)
        {
            await apiClient.Delete(@$"/api/movies/{id}");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveEdited(EditMovieViewModel vm)
        {

            var movie = await apiClient.GetAsync<Movie>($"api/Movies/{vm.Id}");
            movie.Title = vm.Title;
            movie.Rating = vm.Rating;
            movie.Category = vm.Category;
            movie.Description = vm.Description;
            movie.ImageUrl = vm.ImageFile;
            movie.Year = vm.Year;
            movie.Country = vm.Country;
            await apiClient.PutAsync($"api/Movies/{vm.Id}", movie);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveRecorded(RecordMovieViewModel vm)
        {
            var request = mapper.MapRecordingRequest(vm.Id, vm.RecordedAt);
            await apiClient.PostAsync<RecordingDto, RecordingDto>("api/recordings", request);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMovieViewModel model)
        {
            if (ModelState.IsValid)
            {

                var createdMovie = await apiClient.PostAsync<MovieDto, MovieDto>("api/movies", mapper.MapMovieRequest(model));
                if (createdMovie != null && model.IsRecorded)
                {
                    var createdRecording = apiClient.PostAsync<RecordingDto, RecordingDto>("api/recordings", new RecordingDto()
                    {
                        Movie = createdMovie,
                        RecordedAtTime = model.RecordingDate
                    });
                }
                return await Task.FromResult(RedirectToAction("Index"));
            }
            return await Index();

        }

        public async Task<IActionResult> Save(CreateMovieViewModel vm)
        {
            var movie = await apiClient.GetAsync<Movie>($"api/Movies/{vm.Id}");
            movie.Title = vm.Title;
            movie.Rating = vm.Rating;
            movie.Category = vm.Category;
            movie.Description = vm.Description;
            movie.ImageUrl = vm.ImageFile;
            movie.Year = vm.Year;
            movie.Country = vm.Country;
            await apiClient.PutAsync($"api/Movies/{vm.Id}", movie);
            return await Task.FromResult(View("Index"));
        }
        public IActionResult VerifyImageFile(string imageFile)
        {
            if (imageFile.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase) || imageFile.EndsWith(".jpeg", StringComparison.OrdinalIgnoreCase))
                return Json(true);
            return Json("Please select a valid jpeg file");
        }
    }
}

MoviesManagement/MoviesManagement/Controllers/RecordingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using MoviesManagement.Dtos;
using MoviesManagement.Mappers;
using MoviesManagement.Models;

namespace MoviesManagement.Controllers
{
    public class RecordingsController : Controller
    {
        private readonly IApiClient apiClient;
        private readonly ITvItemsMapper mapper;

        public RecordingsController(IApiClient apiClient, ITvItemsMapper mapper)
        {
            this.apiClient = apiClient;
            this.mapper = mapper;
        }
        [HttpPost]
        public async Task<IActionResult> Index(int item)
        {
            var tvItem = await apiClient.GetAsync<TvListingItem>($"api/tvitems/{item}");
            var vm = mapper.MapRecording(tvItem);
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Record(int id)
        {  
            var tvItem = await apiClient.GetAsync<TvListingItem>($"api/tvitems/{id}");
            var request = mapper.MapRecordingRequest(tvItem);
            RecordingDto result = await apiClient.PostAsync<RecordingDto, RecordingDto>("api/recordings", request);
            return RedirectToAction("List");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await apiClient.Delete($"api/Recordings/{id}");
            return RedirectToAction("List");
        }

        public async Task<IActionResult> List()
        {
            var recordings = await apiClient.GetAsync<IEnumerable<Recording>>("api/recordings");

            return View("List", mapper.MapRecordingList(recordings));
        }
    }
}

MoviesManagement/MoviesManagement/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesManagement</title>
    <link rel="stylesheet" href="~/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light mb-5" style="background-color:lightsteelblue">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index"><i class="fas fa-camera"></i></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item active">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Recordings" asp-action="List">Recordings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled" href="#">Disabled</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Movies" asp-action="Index">Login</a>
                        </li>
                    }
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2 search-input" onkeyup="filter()" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
                </form>
                <a class="nav-link" asp-controller="Home" asp-action="LogOff">Log off</a>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>

MoviesManagement/MoviesManagement/Views/Shared/_star.cshtml
@model double
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
    <div class="rating position-relative">
        <i class="fas fa-2x fa-star"></i>
        <p>@Model</p>
    </div>

MoviesManagement/MoviesManagement/Views/Shared/_tvItem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}