MoviesManagement/MoviesManagement/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Movies.Data;
using MoviesManagement.Dtos;
using MoviesManagement.Mappers;
using MoviesManagement.Models;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MoviesManagement.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IApiClient apiClient;
        private readonly ITvItemsMapper mapper;

        public MoviesController(IApiClient apiClient, ITvItemsMapper mapper)
        {
            this.apiClient = apiClient;
            this.mapper = mapper;
        }

        // GET: /<controller>/
        public async Task<IActionResult> Index()
        {
            var movies = await apiClient.GetAsync<IList<Movie>>(@"/api/movies");
            var model = movies.Select(mapper.MapMovie).ToList();
            return View(model);
        }

        public async Task<IActionResult> Create()
        {
            return await Task.FromResult(View("Create"));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var movie = await apiClient.GetAsync<Movie>(@$"/api/movies/{id}");
            var vm = mapper.MapEditMovieRequest(movie);
            vm.Id = movie.Id;
            return await Task.FromResult(View("Edit", vm));
        }

        public async Task<IActionResult> Record(int id)
        {
            var movie = await apiClient.GetAsync<Movie>(@$"/api/movies/{id}");
            var vm = mapper.MapRecordMovieRequest(movie);
            vm.Id = movie.Id;

            return await Task.FromResult(View("Record", vm));

        }
        public async Task<IActionResult> Delete(int id)
        {
            await apiClient.Delete(@$"/api/movies/{id}");
            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveEdited(EditMovieViewModel vm)
        {

            var movie = await apiClient.GetAsync<Movie>($"api/Movies/{vm.Id}");
            movie.Title = vm.Title;
            movie.Rating = vm.Rating;
            movie.Category = vm.Category;
            movie.Description = vm.Description;
            movie.ImageUrl = vm.ImageFile;
            movie.Year = vm.Year;
            movie.Country = vm.Country;
            await apiClient.PutAsync($"api/Movies/{vm.Id}", movie);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> SaveRecorded(RecordMovieViewModel vm)
        {
            var request = mapper.MapRecordingRequest(vm.Id, vm.RecordedAt);
            await apiClient.PostAsync<RecordingDto, RecordingDto>("api/recordings", request);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateMovieViewModel model)
        {
            if (ModelState.IsValid)
            {

                var createdMovie = await apiClient.PostAsync<MovieDto, MovieDto>("api/movies", mapper.MapMovieRequest(model));
                if (createdMovie != null && model.IsRecorded)
                {
                    var createdRecording = apiClient.PostAsync<RecordingDto, RecordingDto>("api/recordings", new RecordingDto()
                    {
                        Movie = createdMovie,
                        RecordedAtTime = model.RecordingDate
                    });
                }
                return await Task.FromResult(RedirectToAction("Index"));
            }
            return await Index();

        }

        public async Task<IActionResult> Save(CreateMovieViewModel vm)
        {
            var movie = await apiClient.GetAsync<Movie>($"api/Movies/{vm.Id}");
            movie.Title = vm.Title;
            movie.Rating = vm.Rating;
            movie.Category = vm.Category;
            movie.Description = vm.Description;
            movie.ImageUrl = vm.ImageFile;
            movie.Year = vm.Year;
            movie.Country = vm.Country;
            await apiClient.PutAsync($"api/Movies/{vm.Id}", movie);
            return await Task.FromResult(View("Index"));
        }
        public IActionResult VerifyImageFile(string imageFile)
        {
            if (imageFile.EndsWith(".jpg", StringComparison.OrdinalIgnoreCase) || imageFile.EndsWith(".jpeg", StringComparison.OrdinalIgnoreCase))
                return Json(true);
            return Json("Please select a valid jpeg file");
        }
    }
}

MoviesManagement/MoviesManagement/ViewComponents/MovieViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MoviesManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesManagement.ViewComponents
{
    public class MovieViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(MovieViewModel model)
        {
            return await Task.FromResult(View(model));
        }
        public async Task<IViewComponentResult> Kupa(MovieViewModel model)
        {
            return await Task.FromResult(View((model)));
        }
    }
}

MoviesManagement/MoviesManagement/Views/Movies/Create.cshtml
@inject MoviesManagement.Helpers.IOptionListService service
@{
    ViewData["Title"] = "Create";
}
@model CreateMovieViewModel

<form action="/" method="post">
    <div class="container">
        <div class="text-center m-5">
            <h1 class="display-4">Create new movie</h1>
        </div>

        <div class="form-group">
            <label for="title">Title</label>
            <input asp-for="Title" class="form-control" type="text" id="title" />
            <span class="text-danger" asp-validation-for="Title"></span>
        </div>


        <div class="form-group">
            <label for="descr">Description</label>
            <textarea asp-for="Description" class="form-control" rows="5" id="descr"></textarea>
            <span class="text-danger" asp-validation-for="Description"></span>
        </div>
        <div class="form-group">
            <label for="rating">Rating</label>
            <input type="number" class="form-control" asp-for="Rating" />
            <span asp-validation-for="Rating" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label for="year">Year</label>
            <select asp-for="Year" class="form-control" id="year" asp-items="@service.GetYears()"></select>
            <span class="text-danger" asp-validation-for="Year"></span>
        </div>

        <div class="form-group">
            <label for="countries"></label>
            <select asp-items="@service.GetCountries()" class="form-control" asp-for="Country"></select>
            <span class="text-danger" asp-validation-for="Country"></span>
        </div>
        <div class="form-group">
            <label for="categories">Category</label>
            <select asp-for="Category" class="form-control" id="categories" asp-items="@service.GetCategories()"></select>
            <span class="text-danger" asp-validation-for="Category"></span>
        </div>

        <div class="form-group">
            <label for="imageFile">Image file</label>
            <input asp-for="ImageFile" type="file" class="form-control-file" id="imageFile" />
            <span class="text-danger" asp-validation-for="ImageFile"></span>
        </div>
        <div class="form-check">
            <input asp-for="IsRecorded" type="checkbox" class="form-check-input" id="recorded" />
            <label for="recorded" class="form-label">Is recorded</label>
            <span class="text-danger" asp-validation-for="IsRecorded"></span>
        </div>
        <div class="form-group">
            <label for="recordingDate">Recording date</label>
            <input asp-for="RecordingDate" class="form-control" type="date" id="recordingDate" />
            <span class="text-danger" asp-validation-for="RecordingDate"></span>
        </div>

        <input asp-for="Id" class="form-control" type="hidden" id="recordingDate" />


        <button class="btn btn-primary float-right" asp-controller="Movies" asp-action="Create">Create</button>


    </div>
</form>

MoviesManagement/MoviesManagement/Views/Movies/Edit.cshtml
@inject MoviesManagement.Helpers.IOptionListService service
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model EditMovieViewModel 
@{
}
    <form action="/" method="post">


        <div class="form-group">
            <label for="Title">Title</label>
            <input class="form-control" asp-for="Title"/>
        </div>

        <div class="form-row">
            <div class="form-group col-md-5">
                <label for="Category">Category</label>
                <select class="form-control" asp-for="Category" asp-items="service.GetCategories()"></select>
            </div>
            <div class="form-group col-md-3">
                <label for="Country">Country</label>
                <input class="form-control" asp-for="Country" />
            </div>

            <div class="form-group col-md-2">
                <label for="Year">Year</label>
                <select asp-for="Year" class="form-control" asp-items="service.GetYears()"> </select>
            </div>
            <div class="form-group col-md-2">
                <label for="Rating">Rating</label>
                <input type="number" class="form-control" asp-for="Rating" />
            </div>
        </div>
        <div class="form-grroup">
            <label for="ImageFile"></label>
            <input asp-for="ImageFile" class="form-control" />
        </div>
        <div class="form-group">
            <label for="description">Decription</label>
            <textarea rows="10" class="form-control"asp-for="Description"></textarea>
        </div>
        <div class="form-row">
            <button class="btn btn-secondary m-1">Cancel</button>
            <button class="btn btn-primary m-1" asp-controller="Movies" asp-action="SaveEdited">Save</button>
        </div>
        
        <input type="hidden" asp-for="Id" />
    </form>

MoviesManagement/MoviesManagement/Views/Movies/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IList<MovieViewModel>
@if (Context.User.Identity.IsAuthenticated)
{
    <div class="container">
        @foreach (var item in @Model)
        {
            <div class="mb-3">


                @await Component.InvokeAsync("Movie", item)
            </div>
        }
    </div>
    <a class="btn btn-primary btn-circle btn-sm" asp-action="Create"><i class="fas fa-plus fa-3x"></i></a>
}

MoviesManagement/MoviesManagement/Views/Movies/Record.cshtml
@model  RecordMovieViewModel

<div>
    <form method="post" action="/">
        <div class="form-group">
            <label>Title</label>
            <input class="form-control" asp-for="MovieTitle" />
        </div>

        <div class="form-group">
            <label>Recorded at</label>
            <input type="date" class="form-control" asp-for="RecordedAt" />
        </div>

        <input type="hidden" asp-for="Id" />
        <div class="form-row">
            <button class="btn btn-primary" asp-controller="Movies" asp-action="SaveRecorded">Save</button>
        </div>
        
    </form>
</div>